---
title: "Data import"
output: github_document
---

```{r, echo=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```



## Data Import: CSVs

Let's import data using the `redr` package.

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```


look at the data

```{r}
litters_df

head(litters_df)
tail(litters_df)
```


```{r, eval = FALSE}
view(litters_df)
```


```{r}
skimr::skim(litters_df)
```




`read_csv` options...

```{r, eval=FALSE}
read_csv("data/FAS_litters.csv", na = c("", "NA", 999, 88), skip = 2)
```


## other file formats 

we need to read in an excel spreadship

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```


```{r, eval=FALSE}
view(mlb_df)
```


```{r}
lotr_words = 
  read_excel( "data/LotR_Words.xlsx",
  range = "B3:D6"
)
```


##Still more formats ...

Read in a SAS dataset.

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```

```{r, eval=FALSE}
view(pulse_df)
```

## Data export

```{r}
write_csv(lotr_words, file = "data/lotr_words_df.csv")
```

## Why not base r???

```{r}
dont_do_this_df = read.csv("data/FAS_litters.csv")
```




